; Build through scripts/build_windows_installer.ps1 (Inno Setup 6.3+).
#if Ver < EncodeVer(6, 3, 0) || Ver >= EncodeVer(7, 0, 0)
  #error Inno Setup 6.3+ (6.x) is required to compile this installer
#endif

#ifndef AppVersion
  #error AppVersion must be supplied by the build script
#endif
#ifndef AppFileVersion
  #error AppFileVersion must be supplied by the build script
#endif
#ifndef SourceDir
  #error SourceDir must point to the PyInstaller onedir bundle
#endif
#ifndef OutputDir
  #error OutputDir must be supplied by the build script
#endif

[Setup]
; Keep this ID stable across releases so updates reuse the installation.
AppId={{27E62938-D88E-4BB1-A631-385CD8B85585}
AppName=MeasureLab
AppVersion={#AppVersion}
VersionInfoVersion={#AppFileVersion}
AppPublisher=MeasureLab maintainers
AppPublisherURL=https://github.com/youtube-at-vach/MeasureLab
AppSupportURL=https://github.com/youtube-at-vach/MeasureLab/issues
AppUpdatesURL=https://github.com/youtube-at-vach/MeasureLab/releases
DefaultDirName={localappdata}\Programs\MeasureLab
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\MeasureLab.exe
SetupIconFile=..\..\app_icon.ico
OutputDir={#OutputDir}
OutputBaseFilename=MeasureLab-v{#AppVersion}-windows-x64-setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; Only this package-owned runtime directory is replaced. Never delete {app}
; recursively: users may keep screenshots or portable config beside the exe.
Type: filesandordirs; Name: "{app}\_internal"

[Files]
Source: "{#SourceDir}\MeasureLab.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\enable_asio.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\disable_asio.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\README_ASIO.txt"; DestDir: "{app}"; Flags: ignoreversion

[UninstallDelete]
; Generated by the bundled ASIO helper, not user measurement data.
Type: files; Name: "{app}\_internal\_sounddevice_data\portaudio-binaries\libportaudio64bit.dll.bak"

[Icons]
Name: "{userprograms}\MeasureLab"; Filename: "{app}\MeasureLab.exe"; WorkingDir: "{app}"
Name: "{userdesktop}\MeasureLab"; Filename: "{app}\MeasureLab.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\MeasureLab.exe"; WorkingDir: "{app}"; Description: "{cm:LaunchProgram,MeasureLab}"; Flags: nowait postinstall skipifsilent unchecked
