[package]
name = "cxxqt-display"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
display-core = { path = "../display-core", features = ["live-audio"] }
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true
