"""Constants for module names used throughout the application."""

# Module Keys (Names)
MODULE_SIGNAL_GENERATOR = "Signal Generator"
MODULE_SPECTRUM_ANALYZER = "Spectrum Analyzer"
MODULE_SOUND_LEVEL_METER = "Sound Level Meter"
MODULE_LUFS_METER = "LUFS Meter"
MODULE_LOOPBACK_FINDER = "Loopback Finder"
MODULE_DISTORTION_ANALYZER = "Distortion Analyzer"
MODULE_ADVANCED_DISTORTION_METER = "Advanced Distortion Meter"
MODULE_NETWORK_ANALYZER = "Network Analyzer"
MODULE_OSCILLOSCOPE = "Oscilloscope"
MODULE_RAW_TIME_SERIES = "Raw Time Series"

MODULE_LOCK_IN_AMPLIFIER = "Lock-in Amplifier"
MODULE_LOCK_IN_HARMONIC_ANALYZER = "Lock-in Harmonic Analyzer"
MODULE_LOCKIN_SPECTRUM_FINDER = "Lock-in Spectrum Finder"
MODULE_FREQUENCY_COUNTER = "Frequency Counter"
MODULE_LOCK_IN_FREQUENCY_COUNTER = "Lock-in Frequency Counter"
MODULE_SPECTROGRAM = "Spectrogram"
MODULE_BOXCAR_AVERAGER = "Boxcar Averager"
MODULE_GONIOMETER = "Goniometer"
MODULE_IMPEDANCE_ANALYZER = "Impedance Analyzer"
MODULE_NOISE_PROFILER = "Noise Profiler"
MODULE_RECORDER_PLAYER = "Recorder / Player"
MODULE_WAVEFORM_LOOP_PLAYER = "Waveform Loop Player"
MODULE_INVERSE_FILTER = "Inverse Filter"
MODULE_TRANSIENT_ANALYZER = "Transient Analyzer"
MODULE_SOUND_QUALITY_ANALYZER = "Sound Quality Analyzer"
MODULE_TIMECODE_MONITOR = "Timecode Monitor & Generator"
MODULE_BNIM_METER = "BNIM Meter"
MODULE_HRTF_PLAYER = "HRTF Player"
MODULE_ULTRASOUND_MODULATOR = "Ultrasound AM Modulator"
MODULE_LINEARITY_ANALYZER = "Linearity Analyzer"
MODULE_1PPS_MONITOR = "1PPS Monitor"
MODULE_STEREO_ALIGNMENT_MONITOR = "Stereo Alignment Monitor"
MODULE_PROCESSOR_BENCHMARK = "Processor Benchmark"
MODULE_SPATIAL_BINAURAL_MIXER = "Spatial Binaural Mixer"

# List of all module keys in the order they should appear in the UI
ALL_MODULE_KEYS = [
    MODULE_SIGNAL_GENERATOR,
    MODULE_SPECTRUM_ANALYZER,
    MODULE_SOUND_LEVEL_METER,
    MODULE_LUFS_METER,
    MODULE_LOOPBACK_FINDER,
    MODULE_DISTORTION_ANALYZER,
    MODULE_ADVANCED_DISTORTION_METER,
    MODULE_NETWORK_ANALYZER,
    MODULE_OSCILLOSCOPE,
    MODULE_RAW_TIME_SERIES,
    MODULE_LOCK_IN_AMPLIFIER,
    MODULE_LOCK_IN_HARMONIC_ANALYZER,
    MODULE_LOCKIN_SPECTRUM_FINDER,
    MODULE_FREQUENCY_COUNTER,
    MODULE_LOCK_IN_FREQUENCY_COUNTER,
    MODULE_SPECTROGRAM,
    MODULE_BOXCAR_AVERAGER,
    MODULE_GONIOMETER,
    MODULE_IMPEDANCE_ANALYZER,
    MODULE_NOISE_PROFILER,
    MODULE_RECORDER_PLAYER,
    MODULE_WAVEFORM_LOOP_PLAYER,
    MODULE_INVERSE_FILTER,
    MODULE_TRANSIENT_ANALYZER,
    MODULE_SOUND_QUALITY_ANALYZER,
    MODULE_TIMECODE_MONITOR,
    MODULE_BNIM_METER,
    MODULE_HRTF_PLAYER,
    MODULE_ULTRASOUND_MODULATOR,
    MODULE_LINEARITY_ANALYZER,
    MODULE_1PPS_MONITOR,
    MODULE_STEREO_ALIGNMENT_MONITOR,
    MODULE_SPATIAL_BINAURAL_MIXER,
    MODULE_PROCESSOR_BENCHMARK,
]

EXPERIMENTAL_MODULE_KEYS: list[str] = [
]
