[package]
name = "display-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
probe-core.workspace = true
graph-core = { path = "../graph-core" }
audio-core = { path = "../audio-core" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["float_roundtrip"] }
