import pytest
from scipy import signal
from src.core.fft_manager import fft_manager
from src.core.analysis import get_cached_window

def test_available_windows_list():
    """Verify that FFTManager returns a list of windows that can be generated by scipy."""
    windows = fft_manager.get_available_windows()
    assert len(windows) > 0
    assert "hann" in windows
    assert "hamming" in windows
    assert "blackman" in windows
    
    # Check that all returned windows are valid in scipy
    for win_name in windows:
        try:
            # Try to generate a small window
            win = get_cached_window(win_name, 128)
            assert len(win) == 128
        except Exception as e:
            pytest.fail(f"Failed to generate window '{win_name}': {e}")

def test_window_consistency():
    """Verify standard windows behave as expected."""
    # Boxcar (Rectangular) should be all ones
    boxcar = get_cached_window("boxcar", 100)
    assert (boxcar == 1.0).all()
    
    # Hann should be zero at ends (for standard definition, though scipy implementation details vary on endpoint)
    # scipy.signal.windows.hann(M, sym=True) is default.
    hann = get_cached_window("hann", 100)
    assert hann.max() == 1.0
