name: PDF Draft

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '**/*.md'
              - 'mkdocs.yml'
              - 'requirements-docs.txt'
              - '.github/workflows/pdf_draft.yml'

  build-pdf:
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install system dependencies for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0 fonts-noto-cjk

      - name: Install MkDocs and plugins
        run: |
          pip install -r requirements-docs.txt

      - name: Build Docs
        env:
          ENABLE_PDF_EXPORT: 1
        run: mkdocs build

      - name: Rename Output Files
        run: |
          mv site/pdf/operation_manual.pdf site/pdf/operation_manual_ja.pdf
          mv site/en/pdf/operation_manual.pdf site/en/pdf/operation_manual_en.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: manual-pdf
          path: |
            site/pdf/operation_manual_ja.pdf
            site/en/pdf/operation_manual_en.pdf
          retention-days: 5
